FROM php:7.2-apache
#installing git
RUN apt-get install -y git
#installing curl
RUN apt-get install -y curl
#installing nodejs 
RUN curl -s https://deb.nodesource.com/setup_11.x | bash -
RUN apt-get install -y nodejs
#installing composer
RUN curl -s https://getcomposer.org/installer | php
RUN mv composer.phar /usr/local/bin/composer
# create your own directory within that docker container
RUN mkdir /var/www/html/php72 


RUN usermod -u 1000 www-data

#creating a virtual host for our project

ADD ./etc/apache2/sites-available/php72.conf /etc/apache2/sites-available/php72.conf

ADD ./etc/apache2/apache2.conf /etc/apache2/apache2.conf

RUN a2dissite 000-default

RUN a2ensite php72

RUN service apache2 restart
