version: '3.3'

services:

# There are 2 containers
# php56
# php80 // second container~~~

  php72:
    container_name: php72
    build:
      context: .
      dockerfile: Dockerfile.72
    ports:
      - 7008:80
    volumes:
      - /Users/bokehs/Docker/multi-php-container/php72/public:/var/www/html/public

  php80:
    container_name: php80
    build:
      context: .
      dockerfile: Dockerfile.80
    ports:
      - 7009:80
    volumes:
      - /Users/bokehs/Docker/multi-php-container/php80/public:/var/www/html/public
volumes:
  db:
